### ISSUE TITLE
Subschemas not resolved in new versions

### ISSUE THREAD

**Issue by laurynasr** [gregsdennis/openapi#8]
With the changes in 0.3.0 the way we were validating our payloads against schemas broke -- for some reason it does not resolve references to subschemas any more. I have added some tests showing this in my fork: https://github.com/gregsdennis/Graeae/compare/main...laurynasr:Graeae:internal-reference-tests

I'm not sure if this is a bug in Graeae or in JsonSchema.Net -- but the same tests work fine after removing Graeae from the picture.

**Comment by gregsdennis** [comment]
Thanks for the tests.  I'll pull those in on a branch and start looking into them.

**Comment by gregsdennis** [comment]
Okay, let's walk through your tests.  Here's how you should be validating payloads:

```c#
var schemaFileName = GetFile("schema-components.json");
//IBaseDocument schema = JsonSchema.FromFile(schemaFileName);
//SchemaRegistry.Global.Register(schema);
var fileText = File.ReadAllText(schemaFileName);
var openApiDoc = JsonSerializer.Deserialize(fileText, TestSerializerContext.Default.OpenApiDocument);

var options = new EvaluationOptions
{
EvaluateAs = Draft4Support.Draft4Version,
};
await openApiDoc!.Initialize(options.SchemaRegistry);

var componentRef = JsonPointer.Parse("#/components/schemas/outer");
var schema = openApiDoc.Find<JsonSchema>(componentRef);

var fullFileName = GetFile(fileName);
var payloadJson = File.ReadAllText(fullFileName);
var document = JsonDocument.Parse(payloadJson);
//var options = new EvaluationOptions
//{
//	EvaluateAs = Draft4Support.Draft4Version,
//};

//JsonSchema validateSchema = new JsonSchemaBuilder()
//	.Ref(new Uri(schema.BaseUri, componentRef));

var results = schema!.Evaluate(document, options);
Assert.True(results.IsValid);
```

1. Your _schema-components.json_ file isn't a schema; it's closer to an OpenAPI document.  That's the basis of what we'll use to do the validation.  So you'll also need to throw `openapi` and `info` elements in there (because they're required for an OpenAPI doc).  In the test, we deserialize it to `OpenApiDocument`.
2. The next step is to initialize the document.  This sets all of the base URIs appropriately, including on all of the schemas internally.  You don't need to explicitly define a base URI on the document itself, though; the system will generate one for you if you don't.  To initialize the document, it needs a schema registry.  We prefer to use a local registry rather than the global, so we move the options declaration up so that we can use the registry it defines.
3. Find the schema that applies to your data using `.Find<JsonSchema>()` on the OpenAPI document, passing a JSON Pointer to the location of the schema.
4. Validate your payload directly using the schema returned from step 3.

Updating both of the tests this way allows them to pass.

**Comment by gregsdennis** [comment]
I've also added a payload evaluation extension.  See the PR for that.

**Comment by laurynasr** [comment]
> Your schema-components.json file isn't a schema; it's closer to an OpenAPI document.

You're right, that is kind-of a part of an OpenAPI document, which is provided like that (only the `components` object) for Azure API Management: https://learn.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/apis/schemas?pivots=deployment-language-arm-template#schemadocumentproperties-1

But it's also a JSON Schema Draft 4 as well -- and this was what I was basing our code on. I filed this issue because evaluation was working like this with Graeae 0.2.1 -- I have a test repo showing it: https://github.com/laurynasr/graeae-test

I will update our code per your guidelines, but shouldn't it still work without interpreting it as an OpenAPI document?

**Comment by laurynasr** [comment]
> We prefer to use a local registry rather than the global, so we move the options declaration up so that we can use the registry it defines.

That did the trick -- when using local registry everything started working fine with newest Graeae. Thanks!

**Comment by gregsdennis** [comment]
So I think the discrepancy might have to do with [this issue](https://github.com/json-everything/json-everything/issues/753#issuecomment-2187851374) as well.

Pointer dereferencing into unrecognized locations isn't a well-supported scenario.  Since `components` isn't a JSON Schema keyword, it counts as unrecognized.
